[global]
bs=4K
ioengine=posixaio
group_reporting
time_based
ramp_time=5
runtime=35
# TODO could use size= and io_size= if time is screwy? but that would break IOPS anyway
direct=1
slat_percentiles=1
clat_percentiles=1
lat_percentiles=1
percentile_list=0.01:0.1:1:10:20:30:40:50:60:70:80:90:95:99:99.9:99.99
size=64M
io_size=32M
unified_rw_reporting=both

[job1]
name=4k-qd1
iodepth=1
wait_for_previous

#[job2]
#name=4k-qd2
#iodepth=2
#wait_for_previous

[job3]
name=4k-qd4
iodepth=4
wait_for_previous

#[job4]
#name=4k-qd8
#iodepth=8
#wait_for_previous

[job5]
name=4k-qd16
iodepth=16
wait_for_previous

#[job6]
#name=4k-qd32
#iodepth=32
#wait_for_previous

#[job7]
#name=4k-qd64
#iodepth=64
#wait_for_previous

# qd=128 has crazy latency?
#[job8]
#name=4k-qd128
#iodepth=128
#wait_for_previous
